name: Java Build and Release

on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'
  pull_request:
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build (${​{ matrix.label }})
    runs-on: ${​{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            label: linux-amd64
          - os: ubuntu-latest
            arch: arm64
            label: linux-arm64
          - os: windows-latest
            arch: amd64
            label: windows-amd64
          - os: macos-latest
            arch: amd64
            label: macos-amd64
          - os: macos-14
            arch: arm64
            label: macos-arm64

    steps:
      - uses: actions/checkout@v4

      - name: Generate date
        id: build_date
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up GraalVM (Java 21)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: graalvm
          architecture: ${​{ matrix.arch }}
          github-token: ${​{ secrets.GITHUB_TOKEN }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: biliTickerBuy-${​{ steps.build_date.outputs.date }}-${​{ matrix.label }}
          path: |
            target/*-jar-with-dependencies.jar
            target/*-all.jar
            target/*.jar
          retention-days: 5

  release:
    name: Publish Release
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate date
        id: rel_date
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-${​{ steps.rel_date.outputs.date }}
          name: Release ${​{ steps.rel_date.outputs.date }}
          files: release/**/*.jar
        env:
          GITHUB_TOKEN: ${​{ secrets.GITHUB_TOKEN }}
