name: Java Build and Release

on:
  push:
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'
  pull_request:
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build (${{ matrix.label }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            label: linux-amd64
            artifact_name: biliTickerBuy-Linux-x86_64
          - os: ubuntu-latest
            arch: arm64
            label: linux-arm64
            artifact_name: biliTickerBuy-Linux-aarch64
          - os: windows-latest
            arch: amd64
            label: windows-amd64
            artifact_name: biliTickerBuy-Windows-x86_64
          - os: macos-latest
            arch: amd64
            label: macos-amd64
            artifact_name: biliTickerBuy-macOS-x86_64
          - os: macos-14
            arch: arm64
            label: macos-arm64
            artifact_name: biliTickerBuy-macOS-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Generate build info
        id: build_info
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "build_id=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          architecture: ${{ matrix.arch }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}-${{ steps.build_info.outputs.date }}-${{ steps.build_info.outputs.build_id }}
          path: target/*-jar-with-dependencies.jar
          retention-days: 5

  release:
    name: Publish Release
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate release info
        id: release_info
        run: |
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Install 7‑Zip
        run: sudo apt-get update && sudo apt-get install -y p7zip-full

      - name: List workspace after download (debug)
        run: |
          echo "Workspace contents after artifacts download:"
          find . -maxdepth 3 -print

      - name: Compress JARs with 7‑Zip
        run: |
          mkdir -p release
          # Find every JAR (any depth) and compress individually
          find . -type f -name '*.jar' -print0 | while IFS= read -r -d '' jar; do
            base=$(basename "${jar}" .jar)
            echo "Compressing ${jar} -> release/${base}.7z"
            7z a "release/${base}.7z" "${jar}"
          done
          echo "Release assets:"
          ls -l release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.release_info.outputs.version }}-${{ steps.release_info.outputs.date }}-${{ steps.release_info.outputs.build_id }}
          name: Release ${{ steps.release_info.outputs.version }} (${{ steps.release_info.outputs.date }}-${{ steps.release_info.outputs.build_id }})
          files: release/*.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
