name: Java Build and Release

on:
  push:
    branches: [ main ]
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'
  pull_request:
    paths:
      - 'src/main/java/**'
      - '.github/workflows/maven-publish.yml'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build fat-jar
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.build_info.outputs.date }}
      artifact: ${{ steps.name_step.outputs.artifact_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate date
        id: build_info
        shell: bash
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Set artifact name output
        id: name_step
        run: echo "artifact_name=biliTickerBuy-${{ steps.build_info.outputs.date }}" >> $GITHUB_OUTPUT

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: biliTickerBuy-${{ steps.build_info.outputs.date }}
          path: |
            target/*-jar-with-dependencies.jar
            target/*-all.jar
            target/*.jar
          retention-days: 5

  release:
    name: Publish Release
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact }}
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v-${{ needs.build.outputs.date }}
          name: Release ${{ needs.build.outputs.date }}
          files: release/**/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
